###
# Please keep /.mergify.yml synced!
version: 2

jruby_env: &jruby_env
  # By default we have 2 CPUs and 4GB ram available
  # https://circleci.com/docs/2.0/configuration-reference/#resource_class
  JRUBY_OPTS: "--debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"

common_env: &common_env
  # CircleCI container has two cores, but Ruby can see 32 cores. So we
  # configure test-queue.
  # See https://github.com/tmm1/test-queue#environment-variables
  TEST_QUEUE_WORKERS: 2

spec_steps: &spec_steps
  - checkout
  - attach_workspace:
      at: ~/project/tmp
  - run: bundle install
  - run:
      name: Run specs
      command: |
        ./tmp/cc-test-reporter before-build
        COVERAGE=true bundle exec rake spec
        ./tmp/cc-test-reporter format-coverage --output tmp/codecov.$CIRCLE_JOB.json
  - persist_to_workspace:
      root: tmp
      paths:
        - codecov.*.json

ascii_spec_steps: &ascii_spec_steps
  - checkout
  - run: bundle install
  - run: bundle exec rake ascii_spec

rubocop_steps: &rubocop_steps
  - checkout
  - run: bundle install
  - run: bundle exec rake internal_investigation
  - run:
      name: Check requiring libraries successfully
      # See https://github.com/rubocop/rubocop/pull/4523#issuecomment-309136113
      command: |
        ruby -I lib -r bundler/setup -r rubocop -e 'exit 0'

jobs:

  # Ruby 2.5
  ruby-2.5-spec:
    docker:
      - image: circleci/ruby:2.5
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-2.5-ascii_spec:
    docker:
      - image: circleci/ruby:2.5
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps
  ruby-2.5-rubocop:
    docker:
      - image: circleci/ruby:2.5
    environment:
      <<: *common_env
    steps:
      *rubocop_steps

  # Ruby 2.6
  ruby-2.6-spec:
    docker:
      - image: circleci/ruby:2.6
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-2.6-ascii_spec:
    docker:
      - image: circleci/ruby:2.6
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps
  ruby-2.6-rubocop:
    docker:
      - image: circleci/ruby:2.6
    environment:
      <<: *common_env
    steps:
      *rubocop_steps

  # Ruby 2.7
  ruby-2.7-spec:
    docker:
      - image: circleci/ruby:2.7
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-2.7-ascii_spec:
    docker:
      - image: circleci/ruby:2.7
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps
  ruby-2.7-rubocop:
    docker:
      - image: circleci/ruby:2.7
    environment:
      <<: *common_env
    steps:
      *rubocop_steps

  # Ruby 3.0
  ruby-3.0-spec:
    docker:
      - image: circleci/ruby:3.0
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-3.0-ascii_spec:
    docker:
      - image: circleci/ruby:3.0
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps
  ruby-3.0-rubocop:
    docker:
      - image: circleci/ruby:3.0
    environment:
      <<: *common_env
    steps:
      *rubocop_steps

  # ruby-head (nightly snapshot build)
  ruby-head-spec:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-head-ascii_spec:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps
  ruby-head-rubocop:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    environment:
      <<: *common_env
    steps:
      *rubocop_steps

  # JRuby 9.2
  jruby-9.2-spec:
    docker:
      - image: circleci/jruby:9.2
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      *spec_steps
  jruby-9.2-ascii_spec:
    docker:
      - image: circleci/jruby:9.2
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      *ascii_spec_steps
  jruby-9.2-rubocop:
    docker:
      - image: circleci/jruby:9.2
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      *rubocop_steps

  # Job for downloading the Codecov uploader
  cc-setup:
    docker:
      - image: circleci/ruby
    environment:
      <<: *common_env
    steps:
      - run:
          name: Download Codecov Uploader
          command: |
            curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import # One-time step

            mkdir -p tmp/
            cd ./tmp
            curl -0s https://uploader.codecov.io/latest/linux/codecov
            curl -0s https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
            curl -0s https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
            ls -al
            gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
            echo 'gpgv'
            shasum -a 256 -c codecov.SHA256SUM
            echo 'shasum'

            chmod +x ./codecov
            echo 'chmod'
            cd ..
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  # Job for sending coverage reports to Codecov
  cc-upload-coverage:
    docker:
      - image: circleci/ruby
        environment:
          CC_TEST_REPORTER_ID: a11b66bfbb1acdf220d5cb317b2e945a986fd85adebe29a76d411ad6d74ec31f
    environment:
      <<: *common_env
    steps:
      - attach_workspace:
          at: ~/project/tmp
      - run:
          name: Upload coverage results to Codecov
          command: |
            ./tmp/codecov

  # Miscellaneous tasks
  documentation-checks:
    docker:
      - image: circleci/ruby
    environment:
      <<: *common_env
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Check documentation syntax
          command: bundle exec rake documentation_syntax_check

workflows:
  version: 2
  build:
    jobs:
      - documentation-checks
      - cc-setup
      - ruby-2.5-spec:
          requires:
            - cc-setup
      #- ruby-2.5-ascii_spec
      #- ruby-2.5-rubocop
      - ruby-2.6-spec:
          requires:
            - cc-setup
      #- ruby-2.6-ascii_spec
      #- ruby-2.6-rubocop
      - ruby-2.7-spec:
          requires:
            - cc-setup
      #- ruby-2.7-ascii_spec
      #- ruby-2.7-rubocop
      - ruby-3.0-spec:
          requires:
            - cc-setup
      #- ruby-3.0-ascii_spec
      #- ruby-3.0-rubocop
      - ruby-head-spec:
          requires:
            - cc-setup
      #- ruby-head-ascii_spec
      #- ruby-head-rubocop
      - jruby-9.2-spec:
          requires:
            - cc-setup
      #- jruby-9.2-ascii_spec
      #- jruby-9.2-rubocop

      - cc-upload-coverage:
          requires:
            - ruby-2.5-spec
            - ruby-2.6-spec
            - ruby-2.7-spec
            - ruby-3.0-spec
            - jruby-9.2-spec
